DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS hospital;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  dob TIMESTAMP NOT NULL,
  bg TEXT NOT NULL
);

CREATE TABLE hospital (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  password TEXT NOT NULL,
  location TEXT NOT NULL
);
